package animationtest;

import java.io.*;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.Scanner;

import static animationtest.ProgramInfo.ItemData;

public class Export {

    public static void writeTextFile(String code, String filePath) throws FileNotFoundException {
        PrintWriter outFile = new PrintWriter(filePath);

        outFile.write(code);
        outFile.close();
    }

    public static void writeBinaryFile(String fileName, PointArray pointArray) throws IOException {
        FileOutputStream fos = new FileOutputStream(fileName);
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        oos.writeInt(pointArray.size());
        for (Point p : pointArray.getList()) {
            oos.writeObject(p);
        }
    }

    public static String pointArrayToString(PointArray pointArray) {
        String out = "";

        for (int i = 0; i < pointArray.size(); i++) {
            out += pointArray.get(i).toString() + "\n";
        }

        return (out);
    }

    private static PointArray fileToPoints(File f) {
        PointArray rtn = new PointArray();
        Scanner scan;

        try {
            scan = new Scanner(f);

            String aPoint;

            double x, y;
            String code;
            int speed;

            //as long as there are more points
            while (scan.hasNextLine()) {
                //put the line with the next point in a string for processing.
                aPoint = scan.nextLine();

                //extract the information about the point from the string
                x = Double.parseDouble(aPoint.substring(2, aPoint.indexOf(' ')));
                aPoint = aPoint.substring(aPoint.indexOf(' ') + 1);
                y = Double.parseDouble(aPoint.substring(2, aPoint.indexOf(' ')));
                aPoint = aPoint.substring(aPoint.indexOf('\"') + 1);
                code = aPoint.substring(0, aPoint.indexOf('\"'));
                aPoint = aPoint.substring(aPoint.indexOf('[') + 1);
                speed = Integer.parseInt(aPoint.substring(0, aPoint.indexOf(']')));

                //make a new point with the information extracted
                rtn.add(new Point(x, y, code, speed));
            }

            scan.close();
        } catch (FileNotFoundException e) {
            System.out.print("file not found!");
            e.printStackTrace();
        } catch (NumberFormatException e) {
            System.out.print("Illegal file format!");
            e.printStackTrace();
            rtn.clear();
        } finally {
            return rtn;
        }
    }

    public static PointArray readTextFile(String path) {
        return fileToPoints(new File(path));
    }

    public static PointArray readBinaryFile(String path) {
        PointArray rtn = new PointArray();

        try {
            FileInputStream fis = new FileInputStream(path);
            ObjectInputStream ois = new ObjectInputStream(fis);

            int size = ois.readInt();

            for (int i = 0; i < size; i++) {
                rtn.add((Point) ois.readObject());
            }
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }

        return rtn;
    }

    public static String writeProgram(ProgramInfo info) {
        String rtn = "";
        String user = System.getProperty("user.name");

        rtn += "package com.qualcomm.ftcrobotcontroller.opmodes;\n" +
                "\n" +
                "import com.qualcomm.robotcore.eventloop.opmode.OpMode;\n" +
                "import com.qualcomm.robotcore.hardware.DcMotor;\n" +
                "import com.qualcomm.robotcore.hardware.Servo;\n" +
                "\n" +
                "/**\n" +
                " * This op mode was generated by FTC-autoDrawer.\n" +
                " * Code generated from file " + info.getSaveLocation().toString() + ", \n" +
                " * on " + Calendar.getInstance().getTime().toString() + ",\n" +
                " * by " + user + ".\n" +
                " * \n" +
                " * Insert your own documentation here\n" +
                " */\n" +
                "\n\n";

        rtn += "public class " + info.getProgramName() + " extends OpMode { \n\n";

        rtn += "    private final Boolean syncLock = true;\n\n";

        for (ItemData data : info.getMotors()) {
            rtn += "    DcMotor " + data.getProgramName() + ";\n";
            rtn += "    volatile double " + data.getProgramName() + "Power;\n";
        }

        for (ItemData data : info.getServos()) {
            rtn += "    Servo " + data.getProgramName() + ";\n";
            rtn += "    volatile double " + data.getProgramName() + "Position;\n";
        }

        rtn += "    public void start() {\n";

        for (ItemData data : info.getMotors()) {
            rtn += "        " + data.getProgramName() + " = hardwareMap.dcMotor.get(\"" + data.getControllerName() + "\");\n";
            if (data.isReversed())
                rtn += "        " + data.getProgramName() + ".setDirection(DcMotor.Direction.REVERSE);\n";
            rtn += "        " + data.getProgramName() + "Power = 0;\n";
        }

        rtn += "\n";

        for (ItemData data : info.getServos()) {
            rtn += "        " + data.getProgramName() + " = hardwareMap.servo.get(\"" + data.getControllerName() + "\");\n";
            if (data.isReversed())
                rtn += "        " + data.getProgramName() + ".setDirection(Servo.Direction.REVERSE);\n";
        }

        rtn += "    }\n\n";

        rtn += "    public void loop() {\n" +
                "        synchronized (syncLock) {\n";

        for (ItemData data : info.getMotors()) {
            rtn += "            " + data.getProgramName() + ".setPower(" + data.getProgramName() + "Power);\n";
        }

        for (ItemData data : info.getServos()) {
            rtn += "            " + data.getProgramName() + ".setPosition(" + data.getProgramName() + "Position);\n";
        }

        rtn += "        }\n" +
                "    }\n\n" +
                "    public void stop() {\n\n" +
                "    }\n" +
                "    private class " + info.getProgramName() + "Thread extends Thread {\n" +
                "\n" +
                "\n" +
                "        @Override\n" +
                "        public void run() {\n" +
                "            super.run();\n" +
                "\n";

        PointArray points = info.getPointArray();

        if (points.get(0).extraCode != null)
            rtn += "            " + points.get(0).extraCode + "\n";
        for (int i = 0; i < points.size() - 2; i++) {
            rtn += "            autoDrive(" + points.getDistance(i) + ");\n";
            if (points.get(i + 1).extraCode != null)
                rtn += "            " + points.get(i + 1).extraCode + "\n\n";
            rtn += "            autoTurn(" + points.getAngle(i + 1) + ");\n";
        }
        rtn += "            autoDrive(" + points.getDistance(points.size() - 2) + ");\n";
        if (points.get(points.size() - 1).extraCode != null)
            rtn += "            " + points.get(points.size() - 1).extraCode + "\n\n";

        rtn += "        }\n" +
                "\n" +
                "        private void autoDrive(double inches){\n" +
                "            synchronized (syncLock){\n" +
                "                //set motors here\n" +
                "            }\n" +
                "\n" +
                "            //wait code\n" +
                "\n" +
                "            synchronized (syncLock) {\n" +
                "                //stop motors here\n" +
                "            }\n" +
                "        }\n" +
                "\n" +
                "        private void autoTurn(double degrees){\n" +
                "            synchronized (syncLock){\n" +
                "                //set motors here\n" +
                "            }\n" +
                "\n" +
                "            //wait code\n" +
                "\n" +
                "            synchronized (syncLock){\n" +
                "                //stop motors here\n" +
                "            }\n" +
                "        }\n" +
                "    }" +
                "}";

        return rtn;
    }

    public static void main(String[] args) {
        File file = FileChooser.fileChooser("Export", "Export", "Export this file");
        File save = FileChooser.fileChooser("Save Location", "Save", "Save file to this location");

        LinkedList<ItemData> servos = new LinkedList<>();
        LinkedList<ItemData> motors = new LinkedList<>();

        servos.add(new ItemData("arm", "servo_1"));
        servos.add(new ItemData("claw", "servo_6"));
        motors.add(new ItemData("left", "motor_1", false));
        motors.add(new ItemData("right", "motor_2", true));

        ProgramInfo info = new ProgramInfo(fileToPoints(file), file, "Test", servos, motors);

        try {
            PrintWriter writer = new PrintWriter(save);

            writer.print(writeProgram(info));
            writer.flush();
            writer.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
